//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubRestoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int about_id { get; set; }
        public string about_header { get; set; }
        public string about_text { get; set; }
    }
}
