//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubRestoran.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PubRestoranEntities : DbContext
    {
        public PubRestoranEntities()
            : base("name=PubRestoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Olke> Olkes { get; set; }
        public virtual DbSet<Yemey> Yemeys { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Menu_Type> Menu_Type { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Special> Specials { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
    }
}
