//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubRestoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int offer_id { get; set; }
        public string offer_img { get; set; }
        public string offer_header { get; set; }
        public string offer_text { get; set; }
        public Nullable<System.DateTime> offer_date { get; set; }
        public string offer_insides { get; set; }
        public string offer_about_insides { get; set; }
    }
}
