//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubRestoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int post_id { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public string post_insides { get; set; }
        public string post_header { get; set; }
        public string post_text { get; set; }
        public string post_img { get; set; }
        public string post_about_inside { get; set; }
    }
}
