//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubRestoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int special_id { get; set; }
        public string special_percent { get; set; }
        public string special_header { get; set; }
        public string special_text { get; set; }
        public string special_back_img { get; set; }
    }
}
